import { Text, View, StyleSheet } from '@react-pdf/renderer';
import React from 'react';

const styles = StyleSheet.create({
    p: {
        marginBottom: 5,
        fontSize: 9,
        lineHeight: 1.4,
    },
    bold: {
        fontWeight: 'bold',
    },
    italic: {
        fontStyle: 'italic',
    },
    underline: {
        textDecoration: 'underline',
    },
    h1: {
        fontSize: 14,
        fontWeight: 'bold',
        marginBottom: 8,
        marginTop: 10,
    },
    h2: {
        fontSize: 12,
        fontWeight: 'bold',
        marginBottom: 6,
        marginTop: 8,
    },
    ul: {
        marginLeft: 10,
        marginBottom: 5,
    },
    ol: {
        marginLeft: 10,
        marginBottom: 5,
    },
    li: {
        flexDirection: 'row',
        marginBottom: 2,
    },
    bullet: {
        width: 10,
    },
    blockquote: {
        borderLeftWidth: 2,
        borderLeftColor: '#e2e8f0',
        paddingLeft: 10,
        marginLeft: 5,
        fontStyle: 'italic',
        marginBottom: 10,
    }
});

/**
 * A simple HTML to React-PDF parser.
 * This is designed to handle the basic tags generated by Quill.
 */
export const parseHtmlToPdf = (html: string) => {
    if (!html) return null;

    // Use DOMParser to parse the HTML string (Client-side only)
    const parser = new DOMParser();
    const doc = parser.parseFromString(html, 'text/html');

    return Array.from(doc.body.childNodes).map((node, index) =>
        renderNode(node, index)
    );
};

const renderNode = (node: Node, index: number): React.ReactNode => {
    if (node.nodeType === Node.TEXT_NODE) {
        return <Text key={index}>{node.textContent}</Text>;
    }

    if (node.nodeType === Node.ELEMENT_NODE) {
        const element = node as HTMLElement;
        const tagName = element.tagName.toLowerCase();
        const children = Array.from(element.childNodes).map((child, i) => renderNode(child, i));

        switch (tagName) {
            case 'p':
                return <View key={index} style={styles.p}><Text>{children}</Text></View>;
            case 'strong':
            case 'b':
                return <Text key={index} style={styles.bold}>{children}</Text>;
            case 'em':
            case 'i':
                return <Text key={index} style={styles.italic}>{children}</Text>;
            case 'u':
                return <Text key={index} style={styles.underline}>{children}</Text>;
            case 'h1':
                return <Text key={index} style={styles.h1}>{children}</Text>;
            case 'h2':
                return <Text key={index} style={styles.h2}>{children}</Text>;
            case 'br':
                return <Text key={index}>{'\n'}</Text>;
            case 'ul':
                return (
                    <View key={index} style={styles.ul}>
                        {children}
                    </View>
                );
            case 'ol':
                return (
                    <View key={index} style={styles.ol}>
                        {children}
                    </View>
                );
            case 'li':
                const isBullet = element.parentElement?.tagName.toLowerCase() === 'ul';
                return (
                    <View key={index} style={styles.li}>
                        <Text style={styles.bullet}>{isBullet ? '• ' : `${index + 1}. `}</Text>
                        <Text style={{ flex: 1 }}>{children}</Text>
                    </View>
                );
            case 'blockquote':
                return (
                    <View key={index} style={styles.blockquote}>
                        <Text>{children}</Text>
                    </View>
                );
            default:
                // For unknown tags, just render children in a View or Text
                return <View key={index}>{children}</View>;
        }
    }

    return null;
};
